import React, {useMemo, useState} from 'react';
import {SafeAreaView, ScrollView, Text, TextInput, TouchableOpacity, View} from 'react-native';
import {StatusBar} from 'expo-status-bar';

const money = n => 'Rp ' + Number(n || 0).toLocaleString('id-ID');
const today = () => new Date().toISOString().slice(0, 10);
const initialTx = [
  {id: 1, date: today(), type: 'in', cat: 'Income', note: 'Freelance landing page', amount: 750000},
  {id: 2, date: today(), type: 'out', cat: 'Food', note: 'Kopi + nasi ayam', amount: 42000},
];
const nav = ['Landing', 'Login', 'Dashboard', 'Chatbot', 'Split Bill', 'Laporan', 'Budget', 'Admin'];

function parseChat(text) {
  const s = text.toLowerCase();
  const type = /(keluar|jajan|beli|bayar|spent|expense)/.test(s) ? 'out' : 'in';
  const match = text.match(/(?:rp\s*)?([0-9][0-9.]*)/i);
  const amount = match ? Number(match[1].replace(/\./g, '')) : 0;
  let cat = type === 'out' ? 'Lifestyle' : 'Income';
  if (/makan|kopi|food|ayam|nasi/.test(s)) cat = 'Food';
  if (/transport|grab|gojek|bensin/.test(s)) cat = 'Transport';
  if (/gaji|freelance|jualan|income|masuk/.test(s)) cat = 'Income';
  const note = text.replace(/(?:rp\s*)?[0-9][0-9.]*/gi, '').trim() || 'Catatan cepat';
  return {id: Date.now(), date: today(), type, cat, note, amount};
}

function PixelTitle({children, className = ''}) {
  return <Text className={`font-black uppercase tracking-tight text-ink ${className}`}>{children}</Text>;
}
function BrutalCard({children, className = ''}) {
  return <View className={`border-[3px] border-ink bg-white p-5 ${className}`} style={{shadowColor:'#151515', shadowOpacity:1, shadowRadius:0, shadowOffset:{width:7,height:7}, elevation:8}}>{children}</View>;
}
function Button({children, onPress, tone='lime'}) {
  const bg = tone === 'pink' ? 'bg-pink' : tone === 'cyan' ? 'bg-cyan' : tone === 'dark' ? 'bg-ink' : 'bg-lime';
  const fg = tone === 'dark' || tone === 'pink' ? 'text-white' : 'text-ink';
  return <TouchableOpacity onPress={onPress} className={`border-[3px] border-ink px-4 py-3 ${bg}`} style={{shadowColor:'#151515', shadowOpacity:1, shadowRadius:0, shadowOffset:{width:4,height:4}, elevation:5}}><Text className={`font-black text-center ${fg}`}>{children}</Text></TouchableOpacity>;
}
function Kicker({children}) {return <Text className="self-start border-2 border-ink bg-cyan px-3 py-2 font-black text-ink">{children}</Text>}
function Stat({label, value, color}) {return <View className={`flex-1 min-w-[145px] border-[3px] border-ink p-4 ${color}`} style={{shadowColor:'#151515', shadowOpacity:1, shadowRadius:0, shadowOffset:{width:4,height:4}, elevation:4}}><Text className="text-xs font-black uppercase text-ink">{label}</Text><Text className="mt-2 text-2xl font-black text-ink">{value}</Text></View>}
function Input(props){return <TextInput placeholderTextColor="#5e5147" className="border-2 border-ink bg-[#fffaf0] px-3 py-3 font-bold text-ink" {...props}/>}

function Landing({go}) {return <ScrollView className="bg-paper"><View className="px-4 py-6"><View className="flex-row items-center justify-between"><View className="flex-row items-center gap-3"><View className="h-11 w-11 items-center justify-center border-[3px] border-ink bg-lime"><Text className="font-black">UM</Text></View><Text className="text-2xl font-black text-ink">UangMasuk</Text></View><Button onPress={()=>go('Login')}>Mulai</Button></View><View className="mt-12"><Kicker>8-BIT MONEY TRACKER</Kicker><PixelTitle className="mt-5 text-5xl leading-[48px]">Keuangan Gen Z yang gak bikin pusing.</PixelTitle><Text className="mt-5 text-base font-bold leading-7 text-muted">Catat pemasukan, jajan, split bill, budget, laporan, sampai chatbot input otomatis. Tinggal ketik: “beli kopi 18000”, datanya langsung masuk.</Text><View className="mt-6 flex-row flex-wrap gap-3"><Button onPress={()=>go('Login')}>Mulai Gratis</Button><Button tone="cyan" onPress={()=>go('Dashboard')}>Coba Dashboard</Button></View></View><BrutalCard className="mt-10 bg-paper2"><View className="border-[3px] border-ink bg-ink p-4"><Text className="mb-2 text-lg font-black text-lime">&gt; jajan kopi 18.000</Text><Text className="mb-2 text-lg font-black text-white">OK expense: Food / Rp18.000</Text><Text className="mb-2 text-lg font-black text-cyan">&gt; split bill 150.000: Sae,Dya,Raka</Text><Text className="text-lg font-black text-pink">PAY Rp50.000/orang</Text></View></BrutalCard><View className="mt-10 gap-4"><Feature title="Chatbot Input" text="Ketik natural, transaksi otomatis terbaca."/><Feature title="Split Bill" text="Bagi tagihan nongkrong cepat dan rapi."/><Feature title="Budget & Goals" text="Target tabungan, limit jajan, dan insight."/></View></View></ScrollView>}
function Feature({title,text}){return <BrutalCard><Text className="text-2xl font-black text-ink">{title}</Text><Text className="mt-2 font-bold text-muted">{text}</Text></BrutalCard>}

function Login({go}) {const [tab,setTab]=useState('Login'); return <View className="flex-1 justify-center bg-paper px-4"><BrutalCard><View className="flex-row items-center gap-3"><View className="h-11 w-11 items-center justify-center border-[3px] border-ink bg-lime"><Text className="font-black">UM</Text></View><Text className="text-2xl font-black">UangMasuk</Text></View><PixelTitle className="mt-6 text-4xl">Akses Akun</PixelTitle><Text className="mt-2 font-bold text-muted">Login, daftar, lupa password, dan OTP tetap ada.</Text><View className="mt-5 flex-row flex-wrap gap-2">{['Login','Register','Lupa','OTP'].map(x=><TouchableOpacity key={x} onPress={()=>setTab(x)} className={`border-2 border-ink px-3 py-2 ${tab===x?'bg-lime':'bg-white'}`}><Text className="font-black">{x}</Text></TouchableOpacity>)}</View><View className="mt-5 gap-3"><Input placeholder={tab==='OTP'?'Kode OTP':'Email'} keyboardType="email-address"/><Input placeholder={tab==='Register'?'Nama kamu':'Password'} secureTextEntry={tab==='Login'}/><Button tone={tab==='Lupa'?'pink':'lime'} onPress={()=>go('Dashboard')}>{tab==='Login'?'Masuk Demo':tab==='Register'?'Buat Akun':tab==='OTP'?'Verifikasi':'Kirim Link'}</Button></View></BrutalCard></View>}

function Dashboard({tx,setTx,go}) {const totals=useMemo(()=>{const inc=tx.filter(x=>x.type==='in').reduce((a,b)=>a+b.amount,0);const out=tx.filter(x=>x.type==='out').reduce((a,b)=>a+b.amount,0);return{inc,out,bal:inc-out,count:tx.length}},[tx]);return <Screen title="Dashboard"><View className="flex-row flex-wrap gap-3"><Stat label="Pemasukan" value={money(totals.inc)} color="bg-lime"/><Stat label="Pengeluaran" value={money(totals.out)} color="bg-pink"/><Stat label="Balance" value={money(totals.bal)} color="bg-cyan"/><Stat label="Transaksi" value={totals.count} color="bg-paper2"/></View><ChatPanel setTx={setTx}/><TxTable tx={tx} setTx={setTx}/></Screen>}
function ChatPanel({setTx}){const [text,setText]=useState('');const [msg,setMsg]=useState('Ketik transaksi natural untuk auto input.');function add(v=text){const item=parseChat(v);setTx(t=>[item,...t]);setMsg(`OK! ${item.type==='out'?'Pengeluaran':'Pemasukan'} ${money(item.amount)} kategori ${item.cat} sudah dicatat.`);setText('')}return <BrutalCard className="mt-5"><Text className="text-2xl font-black">Chatbot Cepat</Text><View className="mt-3 gap-3"><Input value={text} onChangeText={setText} placeholder="contoh: jajan kopi 18000"/><Button onPress={()=>add()}>Input</Button></View><Text className="mt-3 border-2 border-ink bg-paper2 p-3 font-bold">{msg}</Text><View className="mt-3 flex-row flex-wrap gap-2">{['jajan kopi 18000','masuk freelance 750000','beli nasi ayam 25000'].map(s=><TouchableOpacity key={s} onPress={()=>add(s)} className="border-2 border-ink bg-white px-3 py-2"><Text className="font-black">{s}</Text></TouchableOpacity>)}</View></BrutalCard>}
function TxTable({tx,setTx}){return <BrutalCard className="mt-5"><Text className="mb-3 text-2xl font-black">Transaksi Terbaru</Text>{tx.map(x=><View key={x.id} className="mb-3 border-2 border-ink bg-[#fffaf0] p-3"><View className="flex-row justify-between"><Text className="font-black">{x.cat}</Text><Text className={`border-2 border-ink px-2 font-black ${x.type==='out'?'bg-red text-white':'bg-green text-ink'}`}>{x.type==='out'?'Keluar':'Masuk'}</Text></View><Text className="mt-1 font-bold text-muted">{x.date} • {x.note}</Text><View className="mt-2 flex-row items-center justify-between"><Text className="text-xl font-black">{money(x.amount)}</Text><TouchableOpacity onPress={()=>setTx(t=>t.filter(y=>y.id!==x.id))} className="border-2 border-ink bg-white px-3 py-1"><Text className="font-black">hapus</Text></TouchableOpacity></View></View>)}</BrutalCard>}
function Chatbot({tx,setTx}) {const [amount,setAmount]=useState(''); const [note,setNote]=useState(''); return <Screen title="Chatbot & Transaksi"><BrutalCard><Text className="text-2xl font-black">Input Manual</Text><View className="mt-3 gap-3"><Input placeholder="Nominal" keyboardType="numeric" value={amount} onChangeText={setAmount}/><Input placeholder="Catatan" value={note} onChangeText={setNote}/><Button onPress={()=>{setTx(t=>[{id:Date.now(),date:today(),type:'out',cat:'Manual',note:note||'Manual',amount:Number(amount)||0},...t]);setAmount('');setNote('')}}>Simpan</Button></View></BrutalCard><ChatPanel setTx={setTx}/><TxTable tx={tx} setTx={setTx}/></Screen>}
function SplitBill(){const [total,setTotal]=useState('');const [names,setNames]=useState('Sae, Dya, Raka');const people=names.split(',').map(x=>x.trim()).filter(Boolean);const each=people.length?Math.ceil((Number(total)||0)/people.length):0;return <Screen title="Split Bill"><BrutalCard><Text className="text-2xl font-black">Split Bill</Text><View className="mt-3 gap-3"><Input value={total} onChangeText={setTotal} keyboardType="numeric" placeholder="Total tagihan"/><Input value={names} onChangeText={setNames} placeholder="Nama, pisahkan koma"/></View><View className="mt-4 gap-3">{people.map(p=><Text key={p} className="border-2 border-ink bg-paper2 p-3 font-black">{p}: {money(each)}</Text>)}</View></BrutalCard></Screen>}
function Budget(){return <Screen title="Budget & Goals"><BrutalCard><Text className="text-2xl font-black">Dana darurat</Text><Text className="mt-2 font-bold">Rp 850.000 / Rp 3.000.000</Text><View className="mt-3 h-5 border-2 border-ink bg-white"><View className="h-full w-[28%] bg-lime"/></View><Text className="mt-2 font-black">28%</Text></BrutalCard><BrutalCard className="mt-5"><Text className="text-2xl font-black">Catatan Gen Z</Text><Input multiline className="mt-3 min-h-[120px] border-2 border-ink bg-[#fffaf0] px-3 py-3 font-bold text-ink" placeholder="Tulis rencana uang kamu..."/></BrutalCard></Screen>}
function Admin(){return <Screen title="Admin"><View className="flex-row flex-wrap gap-3"><Stat label="Users" value="128" color="bg-lime"/><Stat label="Plan Pro" value="24" color="bg-cyan"/><Stat label="Server" value="OK" color="bg-paper2"/><Stat label="Alerts" value="0" color="bg-pink"/></View><BrutalCard className="mt-5"><Text className="text-2xl font-black">Admin Control</Text><Text className="mt-3 border-2 border-ink bg-paper2 p-3 font-black">Kelola Akun</Text><Text className="mt-3 border-2 border-ink bg-paper2 p-3 font-black">Status Server</Text><Text className="mt-3 border-2 border-ink bg-paper2 p-3 font-black">Audit Log</Text></BrutalCard></Screen>}
function Screen({title,children}){return <ScrollView className="bg-paper"><View className="px-4 py-5"><Kicker>GENZ FINANCE OS</Kicker><PixelTitle className="mt-4 text-4xl">{title}</PixelTitle><View className="mt-5">{children}</View></View></ScrollView>}

export default function App(){const [page,setPage]=useState('Landing');const [tx,setTx]=useState(initialTx);let content={Landing:<Landing go={setPage}/>,Login:<Login go={setPage}/>,Dashboard:<Dashboard tx={tx} setTx={setTx} go={setPage}/>,Chatbot:<Chatbot tx={tx} setTx={setTx}/>, 'Split Bill':<SplitBill/>, Laporan:<Dashboard tx={tx} setTx={setTx}/>, Budget:<Budget/>, Admin:<Admin/>}[page];return <SafeAreaView className="flex-1 bg-paper"><StatusBar style="dark"/><View className="border-b-[3px] border-ink bg-paper px-3 py-2"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{nav.map(n=><TouchableOpacity key={n} onPress={()=>setPage(n)} className={`border-2 border-ink px-3 py-2 ${page===n?'bg-lime':'bg-white'}`}><Text className="font-black text-ink">{n}</Text></TouchableOpacity>)}</ScrollView></View>{content}</SafeAreaView>}
